sudo: required
services:
    -docker

scripts:
    - docker build -t gvadrevu/node .
    - docker images gvadrevu/node

before_deploy:
    -docker login -u gvadrevu -p V1@2d3revu

deploy:
    provider: script
    script: docker push gvadrevu/node
    on: 
        branch: master